spring.application.name=HealthyFoodStore

spring.datasource.url=jdbc:mysql://localhost:3306/healthy_food_store
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

logging.level.org.springframework.security=TRACE

razorpay.key.id= rzp_test_TQu2VIEM9smf9A
razorpay.key.secret= K0LZuoQB7JkjbOJ0cJx4K705

# =====================================================
# EMAIL CONFIGURATION
# =====================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=geetika.bait26@gmail.com
spring.mail.password=ayhg cexr rggs djmd

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# ================================
# MSG91 Configuration
# ================================

msg91.auth-key=564947AbQJxnaIEv6a900ad8P1
msg91.template-id=6a900e075880063ccf01cf02
msg91.otp-url=https://control.msg91.com/api/v5/otp